child_process = require "child_process"

spawn = (procName, opts, silent=false) ->
  proc = child_process.spawn procName, opts
  unless silent
    proc.stdout.on 'data', (data) -> process.stdout.write data
    proc.stderr.on 'data', (data) -> process.stderr.write data
  proc


task 'build', 'build usable js file with duo', ->
  spawn 'coffee', ['index.coffee']
